# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbc880f45fbe771f024be2e47ad74451a0dbb51a434e18dafa48f803012ab198c4b0c14df13db3d2ed0e4a88133b9131304e2611b23f79ea2d6eb394fd2a9c0b

test:
  secret_key_base: 6690ef44bb7a2906fdb7dbe4763a5b0617cdc45d113631bc7f7978138e2eb2f5414f9585f1b76d4ddce1d8ffbc7c8dc787b21fa3b22eaae01dcae2de72d3b9c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
